<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>save-reader</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="PKHeX.Core">
      <HintPath>vendor\PKHeX.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
